services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    restart: always

  backend:
    build:
      context: ./backend/demo
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
    - SPRING_DATASOURCE_URL=jdbc:sqlserver://cooking-sql.cv8m6gs80lzf.ap-southeast-2.rds.amazonaws.com:1433;databaseName=cooking;encrypt=false;trustServerCertificate=true
    - SPRING_DATASOURCE_USERNAME=admin
    - SPRING_DATASOURCE_PASSWORD=1234509867
    - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.microsoft.sqlserver.jdbc.SQLServerDriver
    - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.SQLServerDialect
    - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    restart: always

volumes:
  mssql_data:
